/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useLoader, useFrame } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useLoader(
    GLTFLoader,
    "/game_pieces.glb"
  );

  const [active, setActive] = useState(false);
  useEffect(() => {
    document.body.style.cursor = active ? "pointer" : "default";
    return function cleanup() {
      document.body.style.cursor = "default";
    };
  }, [active]);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.Red}
        geometry={nodes.TitlePlane.geometry}
        name="TitlePlane"
      />
      <group name="Game_Over" position={[-0.01, 0.4, 0.18]}>
        <mesh
          material={materials.MaskPlaneMaterial}
          geometry={nodes.GameOver_0.geometry}
          name="GameOver_0"
        />
        <mesh
          material={materials.WhiteEmission}
          geometry={nodes.GameOver_1.geometry}
          name="GameOver_1"
        />
      </group>
      <mesh
        material={materials.MaskPlaneMaterial}
        geometry={nodes.MaskPlane.geometry}
        name="MaskPlane"
        position={[0.02, 0, 0.04]}
      />
    </group>
  );
}
