/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useLoader, useFrame } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useLoader(
    GLTFLoader,
    "/game_pieces.glb"
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <group name="Point" position={[0.93, 4.35, -1.48]} />

        <mesh
          material={materials.MaskPlaneMaterial}
          geometry={nodes.MaskPlane.geometry}
          name="MaskPlane"
        />
        <group
          name="YouWin"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.55, 1.55, 1.55]}
        >
          <mesh
            material={materials.MaskPlaneMaterial}
            geometry={nodes.YouWin_0.geometry}
            name="YouWin_0"
          />
          <mesh
            material={materials.WhiteEmission}
            geometry={nodes.YouWin_1.geometry}
            name="YouWin_1"
          />
        </group>

        {/* <mesh
          material={materials.Green}
          geometry={nodes.WinPlane.geometry}
          name="WinPlane"
          position={[0, 0, -1.14]}
        /> */}
      </scene>
    </group>
  );
}
