/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useLoader, useFrame } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

import { useSpring, animated } from "react-spring/three";

export default function Model(props) {
  const group = useRef();
  const [active, setActive] = useState(false);
  const [clicked, setClicked] = useState(false);
  const { nodes, materials, animations } = useLoader(
    GLTFLoader,
    "/game_pieces.glb"
  );

  const { buttonPosition } = useSpring({
    config: { duration: 100 },
    buttonPosition: clicked ? [0, 0, 0] : [0, 1, 0]
  });

  useEffect(() => {
    document.body.style.cursor = active ? "pointer" : "default";
  }, [active]);

  useEffect(() => {
    if (clicked) {
      setTimeout(() => setClicked(false), 50);
    }
  }, [clicked]);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.Hole}
        geometry={nodes.Button.geometry}
        name="Button"
      >
        <animated.group
          name="ButtonButton"
          position={buttonPosition}
          scale={[0.8, 0.8, 0.8]}
          onClick={() => setClicked(true)}
          onPointerOver={() => setActive(true)}
          onPointerOut={() => setActive(false)}
        >
          <mesh
            material={materials.Button}
            geometry={nodes.ButtonButton_0.geometry}
            name="ButtonButton_0"
          />
          <mesh
            material={materials.MaskPlaneMaterial}
            geometry={nodes.ButtonButton_1.geometry}
            name="ButtonButton_1"
          />
          <mesh
            material={materials.MetalEdge}
            geometry={nodes.ButtonButton_2.geometry}
            name="ButtonButton_2"
          />
        </animated.group>
      </mesh>
    </group>
  );
}
